// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVPOqcxOnV1LMYXc3oKmmEqtjL1q1B7BA',
    appId: '1:118952615694:web:09a422df6151be2ba5015f',
    messagingSenderId: '118952615694',
    projectId: 'valet-club-ba741',
    authDomain: 'valet-club-ba741.firebaseapp.com',
    storageBucket: 'valet-club-ba741.appspot.com',
    measurementId: 'G-CBL7NHKYG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC64qXdqc2ugkj1PfCtLGCBXnPOXDy9PMQ',
    appId: '1:118952615694:android:38e50d5c592971a4a5015f',
    messagingSenderId: '118952615694',
    projectId: 'valet-club-ba741',
    storageBucket: 'valet-club-ba741.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaN2-ey9loJjZAyvWVFl3PmQv2php2sMw',
    appId: '1:118952615694:ios:5adbfd65e79c0134a5015f',
    messagingSenderId: '118952615694',
    projectId: 'valet-club-ba741',
    storageBucket: 'valet-club-ba741.appspot.com',
    iosBundleId: 'com.example.valet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaN2-ey9loJjZAyvWVFl3PmQv2php2sMw',
    appId: '1:118952615694:ios:f555a0fb52971711a5015f',
    messagingSenderId: '118952615694',
    projectId: 'valet-club-ba741',
    storageBucket: 'valet-club-ba741.appspot.com',
    iosBundleId: 'com.example.valet.RunnerTests',
  );
}
